### ISSUE TITLE
How do I prepopulate with existing  data

### ISSUE THREAD

**Issue by andre-artus** [jkuatdsc/form-builder#19]
If I have an update form that I wish to prepopulate with data which method should be called. Or is there a need to create the setData equivalent of getData on FormState?

**Comment by LinusMuema** [comment]
Hi @andre-artus 

Sorry for the late replies. At the moment, only the `TextFieldState` has that provision using the `initial` parameter. You can pass in the initial value of that specific state. We will work on adding this to all other states then close this issue. 😃

**Comment by andre-artus** [comment]
Thanks.

**Comment by OtienoSamwel** [comment]
We found a bug with the quoted implementation. We have made a fix and added the initial state 
parameter to all the form states.

Please refer to the new implementation.

> https://github.com/jkuatdsc/form-builder/blob/9ce799cf377a24872cb7459ae70bd24a83f695e3/example/src/main/java/com/dsc/formbuilder/MainViewModel.kt#L13-L46

**Comment by andre-artus** [comment]
Thank you. I've been a bit busy with other tasks, but I am keen to try this out.

**Comment by andre-artus** [comment]
Is there an integration with autocomplete planned?
