### ISSUE TITLE
Broken Logic on Select State

### ISSUE THREAD

**Issue by jumaallan** [jkuatdsc/form-builder#23]
The `SelectState` is broken on the app. It doesn't update the values when I click a new value on the checkbox

[device-2022-07-22-172359.webm](https://user-images.githubusercontent.com/25085146/180472037-4220768b-2f44-49bc-af59-16e47ad70a4b.webm)

**Comment by OtienoSamwel** [comment]
Hello @jumaallan we have made a fix for this issue in #24. We will be adding tests to the code to prevent such occurrences in the future.
