### ISSUE TITLE
Custom regex validation

### ISSUE THREAD

**Issue by LucaBL** [jkuatdsc/form-builder#57]
Hello, I'm a bit confused on how to use the Custom validator since I couldn't find examples where it is used.
For example, if I have a regex string and want to add a Validators.Custom to a TextFieldState that checks whether the content of a TextField matches it, how should I do that?
Thank you!

**Comment by LinusMuema** [comment]
Hello @LucaBL 

I hope you closed this issue because you found a solution. If you still need help with the problem we are happy to assist you.
